### PR TITLE
Fix #1: Use net-browserify-stub in the browser

### LINKED ISSUE #1: Replace with net-browserify/require net-browserify

### PR DESCRIPTION
**Pull request by frankier**
This provides the isip\* functions. 

Back story/use case: I'm trying to use request/request which supposedly has intermittently worked with browserify. It uses tough-cookie which uses net but only for isip\* functions.

Ref: https://github.com/goinstant/tough-cookie/blob/c66bebadd634f4ff5d8a06519f9e0e4744986ab8/lib/cookie.js

### CODE REVIEW

**Comment by guybedford** [comment]
Amazing, thank you so much.

**Comment by guybedford** [comment]
What is the reason for not using https://github.com/emersion/net-browserify directly? Just thinking about maintenance.

**Comment by frankier** [comment]
I got a node-gyp error with one its dependencies. Connect isn't compatible out of the box, you need to to setup a server. My feeling was it'd be easier to gut it to something that was pure js and point people at emersion/nodelibs-net so they could override it since they're going to have to go through the work out setting up the server component anyway.

**Comment by guybedford** [comment]
Ah I see what you mean. Could we not disable the express side of it through some overrides that remove the dependencies and maps that set the modules to empty perhaps? Just thinking of maintenance here.

**Comment by guybedford** [comment]
@frankier I was able to use the browserify version by adding this override - https://github.com/jspm/registry/blob/master/package-overrides/npm/net-browserify%400.1.6.json.

I've published the fix with a `0.1.1`. Let me know if that works ok for you. Thanks again for picking this up.

**Pull request merged**
